name: GitHub CI

on: [push, pull_request]

jobs:
  tests:

    name: PHP ${{ matrix.php-versions }} Test

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        php-versions: ['7.2', '7.3', '7.4']

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: bcmath, ctype, dom, fileinfo, gd, json, mbstring, openssl, xml, zip
        coverage: none

    - name: Copy .env
      run: cp .env.testing .env

    - name: Install composer
      run: composer test

    - name: Execute tests
      run: vendor/bin/phpunit
